const { v4: uuidv4 } = require("uuid");

let users = [
  {
    uuid: uuidv4(),
    bootcamperId: 1234,
    firstName: "Aftab",
    surname: "Hussain",
    role: "bootcamper",
    cohortNo: 4,
    email: "aftabhussainprojects@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1235,
    firstName: "Alice",
    surname: "Holden",
    role: "bootcamper",
    cohortNo: 4,
    email: "alice-holden@outlook.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1236,
    firstName: "Amelia",
    surname: "Collins-Patel",
    role: "bootcamper",
    cohortNo: 4,
    email: "ameliacollinspatel@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1237,
    firstName: "Will",
    surname: "Edwards",
    role: "bootcamper",
    cohortNo: 4,
    email: "ukbilleh@googlemail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1238,
    firstName: "Anna",
    surname: "Griffin",
    role: "bootcamper",
    cohortNo: 4,
    email: "annagriffin@blueyonder.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1239,
    firstName: "Anna-Marie",
    surname: "Moss",
    role: "bootcamper",
    cohortNo: 4,
    email: "ambrown1976@googlemail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1240,
    firstName: "Arshi",
    surname: "Sheikh",
    role: "bootcamper",
    cohortNo: 4,
    email: "a-sheikh@outlook.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1241,
    firstName: "Becky",
    surname: "Jones",
    role: "coach",
    cohortNo: 4,
    email: "beckyljones151192@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1242,
    firstName: "Bradley",
    surname: "Smith",
    role: "bootcamper",
    cohortNo: 4,
    email: "brsm019@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1243,
    firstName: "Bryan",
    surname: "Beale",
    role: "bootcamper",
    cohortNo: 4,
    email: "bryan.beale88@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1244,
    firstName: "Carl",
    surname: "McIntosh",
    role: "coach",
    cohortNo: 4,
    email: "cod3rcarl@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1245,
    firstName: "Charlie",
    surname: "Chandler",
    role: "bootcamper",
    cohortNo: 4,
    email: "cahc22@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1246,
    firstName: "Dan",
    surname: "Smith",
    role: "bootcamper",
    cohortNo: 4,
    email: "up765064@myport.ac.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1247,
    firstName: "Dan",
    surname: "Watson",
    role: "bootcamper",
    cohortNo: 4,
    email: "dan.watson2309@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1248,
    firstName: "Daniela",
    surname: "Leva ",
    role: "bootcamper",
    cohortNo: 4,
    email: "leva.daniela@yahoo.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1249,
    firstName: "Emma",
    surname: "Randle",
    role: "bootcamper",
    cohortNo: 4,
    email: "erandle2211@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1250,
    firstName: "Fadumo",
    surname: "Aideed",
    role: "bootcamper",
    cohortNo: 4,
    email: "fadumo.ahmed.aideed@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1251,
    firstName: "Freshta",
    surname: "Ebrahim",
    role: "bootcamper",
    cohortNo: 4,
    email: "freshtaebrahim@hotmail.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1252,
    firstName: "Hajoo",
    surname: "Chung",
    role: "bootcamper",
    cohortNo: 4,
    email: "hajoo.chung@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1253,
    firstName: "Hazie",
    surname: "Andrews",
    role: "coach",
    cohortNo: 4,
    email: "senchi37@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1254,
    firstName: "Ionut",
    surname: "Predoi",
    role: "bootcamper",
    cohortNo: 4,
    email: "ipredoi27@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1255,
    firstName: "Isabel",
    surname: "Holland",
    role: "bootcamper",
    cohortNo: 4,
    email: "isabelholland90@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1256,
    firstName: "Ismail",
    surname: "Ali",
    role: "bootcamper",
    cohortNo: 4,
    email: "ismailyma01@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1257,
    firstName: "James",
    surname: "Bowler",
    role: "coach",
    cohortNo: 4,
    email: "j.bowler2017@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1258,
    firstName: "Jeremy",
    surname: "Law",
    role: "bootcamper",
    cohortNo: 4,
    email: "jeremylaw2308@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1259,
    firstName: "Jessica",
    surname: "Wilson-Leigh",
    role: "coach",
    cohortNo: 4,
    email: "jesswilsonleigh@googlemail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1260,
    firstName: "Jon",
    surname: "Owens",
    role: "bootcamper",
    cohortNo: 4,
    email: "jonowens84@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1261,
    firstName: "Katie",
    surname: "Hawcutt",
    role: "bootcamper",
    cohortNo: 4,
    email: "katiehawcutt@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1262,
    firstName: "Kawalpreet",
    surname: "Kaur",
    role: "bootcamper",
    cohortNo: 4,
    email: "kaur.sona1992@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1263,
    firstName: "Khang",
    surname: "Khuat",
    role: "bootcamper",
    cohortNo: 4,
    email: "duykhangkhuat@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1264,
    firstName: "Kunmi",
    surname: "Williams",
    role: "coach",
    cohortNo: 4,
    email: "kumswilliams@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1265,
    firstName: "Laura",
    surname: "Ashcroft",
    role: "bootcamper",
    cohortNo: 4,
    email: "laura.ashcroft14@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1266,
    firstName: "Luke",
    surname: "Fantom",
    role: "bootcamper",
    cohortNo: 4,
    email: "luke.fantom@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1267,
    firstName: "Mahdi",
    surname: "Haroun",
    role: "bootcamper",
    cohortNo: 4,
    email: "mahdiharoun93@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1268,
    firstName: "Max",
    surname: "Tillman",
    role: "bootcamper",
    cohortNo: 4,
    email: "maxltillman@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1269,
    firstName: "Michael",
    surname: "Swann",
    role: "bootcamper",
    cohortNo: 4,
    email: "mikeswann@mail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1270,
    firstName: "Natalie",
    surname: "Posteraro",
    role: "bootcamper",
    cohortNo: 4,
    email: "natalieposteraro@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1271,
    firstName: "Patrick",
    surname: "Fleming",
    role: "bootcamper",
    cohortNo: 4,
    email: "patrickjosephfleming@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1272,
    firstName: "Piper",
    surname: "Bates",
    role: "bootcamper",
    cohortNo: 4,
    email: "piperbates42@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1273,
    firstName: "Shanice",
    surname: "Basra",
    role: "bootcamper",
    cohortNo: 4,
    email: "shanicebasra@outlook.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1274,
    firstName: "Stefan",
    surname: "Kudev",
    role: "bootcamper",
    cohortNo: 4,
    email: "stefan.yanchev.kudev@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1275,
    firstName: "Tom",
    surname: "Bennett",
    role: "bootcamper",
    cohortNo: 4,
    email: "tomnbennett2013@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1276,
    firstName: "Tommy",
    surname: "Holt",
    role: "bootcamper",
    cohortNo: 4,
    email: "tommy_holt@icloud.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1277,
    firstName: "Valentina",
    surname: "Militaru",
    role: "bootcamper",
    cohortNo: 4,
    email: "vmilitaru28@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1278,
    firstName: "Zaid",
    surname: "Qarout",
    role: "bootcamper",
    cohortNo: 4,
    email: "za.qa@outlook.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1279,
    firstName: "Chris",
    surname: "Meah",
    role: "coach",
    cohortNo: 4,
    email: "chris@schoolofcode.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1280,
    firstName: "James",
    surname: "Greygoose",
    role: "coach",
    cohortNo: 4,
    email: "james.greygoose@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1281,
    firstName: "Joe",
    surname: "Trodden",
    role: "coach",
    cohortNo: 4,
    email: "joe@mindsetexperts.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1282,
    firstName: "Kyle",
    surname: "Semple",
    role: "coach",
    cohortNo: 4,
    email: "kylesemple96@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1283,
    firstName: "Liz",
    surname: "Kaufman",
    role: "coach",
    cohortNo: 4,
    email: "liz.k@schoolofcode.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1284,
    firstName: "Lizzie",
    surname: "Edrop",
    role: "coach",
    cohortNo: 4,
    email: "liz@schoolofcode.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1285,
    firstName: "Tao",
    surname: "Sharma",
    role: "coach",
    cohortNo: 4,
    email: "tao@schoolofcode.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1286,
    firstName: "Tim",
    surname: "Knight",
    role: "coach",
    cohortNo: 4,
    email: "tim@schoolofcode.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1287,
    firstName: "Ben",
    surname: "Lee",
    role: "coach",
    cohortNo: 4,
    email: "ben@schoolofcode.co.uk",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1287,
    firstName: "Speaker",
    surname: "View",
    role: "coach",
    cohortNo: 4,
    email: "speakerview@gmail.com",
  },
  {
    uuid: uuidv4(),
    bootcamperId: 1287,
    firstName: "Participant",
    surname: "View",
    role: "bootcamper",
    cohortNo: 4,
    email: "participantview@gmail.com",
  },
];

module.exports = users;
